### ISSUE TITLE
Protonmail bridge SMTP timed out STARTTLS

### ISSUE THREAD

**Issue by AckslD** [soywod/himalaya#60] opened 2021-04-05 12:32 UTC
I'm trying to send an email using himalaya through the protonmail bridge but I'm getting the error:
```
internal client error: timed out waiting for connection: Connection error: Could not connect
```
after some time. Any thoughts on what could be going wrong? imap does work fine.

My config is:
```
[proton]
default = true
email = "<MYEMAIL>"

imap-host = "127.0.0.1"
imap-port = 1143
imap-login = "<MYEMAIL>"
imap-passwd-cmd = "echo <IMAP_PWD>"
imap-starttls = true

smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-login = "<MYEMAIL>"
smtp-passwd-cmd = "echo <IMAP_PWD>"
smtp-starttls = true
```
where things inside `<>` are replaced by their actual values.

**Comment by soywod** [comment] 2021-04-05 13:10
Try to remove the `*-starttls` options?

**Comment by AckslD** [comment] 2021-04-05 14:06
@soywod I did try that but got the same issue regardless. Furthermore removing starttls for imap makes it not work with the error:
```
Cannot connect using TLS
 ↳ error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331: 
```

**Comment by soywod** [comment] 2021-04-05 14:27
Strange. Did you try `localhost` instead of `127.0.0.1`? What's the result of a `telnet localhost 1143? Let me check the protonmail bridge documentation meanwhile.

**Comment by AckslD** [comment] 2021-04-05 14:35
`telnet localhost 1143` gives:
```
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
```

**Comment by soywod** [comment] 2021-04-05 14:58
I read the document. They explain how to set up the bridge with Thunderbird, and one point drags my attention: https://protonmail.com/bridge/thunderbird#5. You need to manually accept the self-signed certificate. Maybe it's what is preventing Himalaya to connect.

**Comment by AckslD** [comment] 2021-04-05 15:54
@soywod I have previously accepted the certificate when setting up aerc following [this](https://iptq.io/setup/command-line-email-with-aerc/#setting-up-aerc-with-protonmail). I guess that should still work

**Comment by soywod** [comment] 2021-04-05 16:05
Ah but wait, I misunderstood, your IMAP works well, right? You only have trouble with SMTP?

**Comment by AckslD** [comment] 2021-04-05 16:09
Yes, indeed, output of `telnet 127.0.0.1 1025` is:
```
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 127.0.0.1 ESMTP Service Ready
```

**Comment by soywod** [comment] 2021-04-05 16:27
> @soywod I have previously accepted the certificate when setting up aerc following [this](https://iptq.io/setup/command-line-email-with-aerc/#setting-up-aerc-with-protonmail). I guess that should still work

Did you try to do the same for the SMTP server?

**Comment by soywod** [comment] 2021-04-05 16:44
I will create a Protonmail account to experiment and let you know.

**Comment by soywod** [comment] 2021-04-05 17:16
- I created a paid Protonmail account (needed to use the bridge)
- I installed the bridge and configured my account
- I forced my OS to untrust the self-signed cert by following [the post](https://iptq.io/setup/command-line-email-with-aerc/#setting-up-aerc-with-protonmail) you gave

I was able to list my mails AND to send one using this configuration:

```toml
[proton]
email = "xxx@protonmail.com"

imap-host = "127.0.0.1"
imap-port = 1143
imap-login = "xxx@protonmail.com"
imap-passwd-cmd = "pass show proton"
imap-starttls = true

smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-login = "xxx@protonmail.com"
smtp-passwd-cmd = "pass show proton"
smtp-starttls = true
```

So I can't reproduce your problem :disappointed: I guess it comes from your configuration. I close this issue, feel free to open a discussion if you have news.

**Closed by soywod** 2021-04-05 17:16 UTC
Labels: bug, cli

**Comment by AckslD** [comment] 2021-04-05 19:40
@soywod Thanks a lot for trying! Hmm that is strange. I wonder what is going on. I resinstalled himalaya from himalaya-git and redid the trusting of the certificate but still having the same issue :/

Btw, when you say that you "forced my OS to untrust the self-signed cert", did you mean "trust"? How did you do this? Using `sudo trust anchor --store protonmail.crt`?

**Comment by soywod** [comment] 2021-04-05 19:58
> How did you do this? Using `sudo trust anchor --store protonmail.crt`?

Yes exactly. I tried without first and I got a STARTTLS self signed certs error. After the command all worked perfectly. I really don't see where it could fail. Which OS do you use?

**Comment by AckslD** [comment] 2021-04-05 20:14
I am on arch linux

**Comment by soywod** [comment] 2021-04-05 20:27
Me too... so I really don't understand xD did you check you didn't do a typo in the Himalaya config?

**Comment by AckslD** [comment] 2021-04-05 20:35
I will double-check tomorrow and try to do some debugging and let you know if I realise something 👍

**Comment by AckslD** [comment] 2021-04-06 10:33
So I checked the config in detail and cannot find an issue. What version of protonmail bridge are you running?
The only difference I can see is that I'm using a custom domain (i.e not @protonmail.com), however not sure that this would be the issus since it works for imap+himalaya and smpt+aerc.

**Comment by soywod** [comment] 2021-04-06 11:24
I used this AUR package: https://aur.archlinux.org/packages/protonmail-bridge-bin/ (v1.6.6-1). Indeed I didn't use a custom domain. Let me know if you find sth!

**Comment by AckslD** [comment] 2021-04-06 11:50
Alright, I use https://aur.archlinux.org/packages/protonmail-bridge-nogui/ (v1.6.9-1). I will for sure let you know, although not completely sure what to try :)

**Comment by srid** [comment] 2021-04-07 00:02
> `sudo trust anchor --store protonmail.crt`

Where is this `trust` command coming from?

**Comment by srid** [comment] 2021-04-07 02:34
I got it to work after setting this environment variable to point to protonmail-bridge's .pem file.

```
SSL_CERT_FILE=~/.config/protonmail/bridge/cert.pem ~/external/himalaya/result/bin/himalaya
```

**Comment by soywod** [comment] 2021-04-07 05:56
> > `sudo trust anchor --store protonmail.crt`
> 
> Where is this `trust` command coming from?

It comes from this article: http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/

**Comment by soywod** [comment] 2021-04-07 05:58
> I got it to work after setting this environment variable to point to protonmail-bridge's .pem file.
> 
> ```
> SSL_CERT_FILE=~/.config/protonmail/bridge/cert.pem ~/external/himalaya/result/bin/himalaya
> ```
> 

@AckslD could you try if it works for you?

**Comment by AckslD** [comment] 2021-04-07 09:21
Thanks for the suggestion @srid. However I get the same error when doing:
```
> (SSL_CERT_FILE=~/.config/protonmail/bridge/cert.pem himalaya write)
(s)end, (d)raft, (e)dit or (q)uit? s
Sending…
internal client error: timed out waiting for connection: Connection error: Could not connect  
```

PS @soywod I think you meant this article: https://iptq.io/setup/command-line-email-with-aerc/#setting-up-aerc-with-protonmail

**Comment by soywod** [comment] 2021-04-07 09:27
> PS @soywod I think you meant this article: https://iptq.io/setup/command-line-email-with-aerc/#setting-up-aerc-with-protonmail

Oups, paste failed :D I fixed the link.
