### ISSUE TITLE
Can't read mail content with out Content-Type

### ISSUE THREAD

**Issue by jheroy** [soywod/himalaya#408] opened 2022-09-05 05:41 UTC
There is my raw mail: 
```
Precedence: list
List-Post: <mailto:xxx@xxx.com>
List-Id: <xxx.com>
Received: from localhost (unknown [xx.xx.xx.xx])
	by mail-m12759.xxx.com (Hmail) with ESMTPA id 504614A019B
	for <xxx@xxx.com>; Sat,  3 Sep 2022 07:02:54 +0800 (CST)
To: xxx@xxx.com
Subject:My test subject
X-HM-Spam-Status: e1kfGhgUHx5xxxxxxxxxxgUHx5ZQUlOS1dZFg8aDwILHllBWSg2Ly
	tZV1koWUFITzdXWS1ZQUlXWQ8xxxxxxxxxxxxhlCTkoZHx5KSkxKQlUTARMWGhIXJBQOD1
	lXWRgSC1lBWU5PVU1DVUhCxxxxxxxxxaDxIVHRRZQVlPS0hVSklLQ05NVUpLS1kG
Message-Id: <20220903070255.504614A019B@xxx.xxx.com>
Date: Sat, 03 Sep 2022 07:02:55 +0800 (GMT+08:00)
From: xxx@xxx.com
X-HM-Sender-Digest: e1kMHhlxxxxxxxxxx4VD1lBWUc6MzI6HRw6Nj0sIjoZNhAKFyId
	Pi8wCTBVSlVKTU1JSk5xxxxxxxxxxxxVRoXHgkPO0wLEgkxxxxxxxxxxGBQWRVlXWRIL
	WUFZTk9VTUNVxxxxxxxxxxxAFZQUpCSzcG
X-HM-Tid: 0a83xxxxxx342xxxxxxx504614a019b

My test content
```

**Comment by fabrixxm** [comment] 2022-09-12 12:09
duplicate of #352 and/or #357 ?

**Comment by soywod** [comment] 2022-09-12 16:24
Indeed, duplicate! Fix is in the pipeline, I let you know whenever it is ready.

**Closed by soywod** 2022-09-12 16:24 UTC
