### ISSUE TITLE
Cannot build sendable message: missing destination address, invalid envelope

### ISSUE THREAD

**Issue by sbromberger** [soywod/himalaya#292] opened 2022-02-08 15:55 UTC
Email addresses are way too complex. :)

In the `To:` field, the following causes an error even though it is/should be valid:

`To: \"Lastname, First\" <me@invalid.com>`

(This was in response to `himalaya reply 3`)

**Comment by soywod** [comment] 2022-02-08 17:53
Duplicate https://github.com/soywod/himalaya/issues/227. I just the way to fix both of them but it will required some time. I let you know!

**Comment by soywod** [comment] 2022-02-09 22:46
I push the fix on `development` branch, could you try again?

**Comment by sbromberger** [comment] 2022-02-12 00:29
Not working:
```
To: "\\"Lastname, Firstname\\"" <email@invalid.net> 
```
yields
```
Error: cannot build sendable message
Caused by:
    missing destination address, invalid envelope
```

**Comment by soywod** [comment] 2022-02-12 01:24
Sure, clement.douin@posteo.net.

**Comment by sbromberger** [comment] 2022-02-12 01:50
Thanks. Sent.

**Comment by soywod** [comment] 2022-02-12 16:44
I was able to reproduce. It looks like another bug from the others. I let you know!

**Comment by soywod** [comment] 2022-02-12 17:34
The issue comes this time from the mailer lib `lettre`. It looks like it treats the comma as the email separator, and then fails because the first chunk at the left of the comma does not contain any email address. I opened an issue there: https://github.com/lettre/lettre.

**Comment by soywod** [comment] 2022-02-12 17:48
Thank you for your patience :smile:

**Comment by soywod** [comment] 2022-02-12 18:58
I got a reply from `lettre`, in fact the issue was already known: https://github.com/lettre/lettre/issues/690

**Comment by sbromberger** [comment] 2022-02-12 19:14
sounds great. Thanks.

**Comment by onguntoglu** [comment] 2022-05-05 16:25
this issue is solved by [lettre/lettre#760](https://github.com/lettre/lettre/pull/760), if I understand correctly

**Comment by soywod** [comment] 2022-05-07 21:06
Awesome, thanks for the update. I will bump the version and check again.

**Comment by TornaxO7** [comment] 2022-05-28 12:27
It looks like that the issue in lettre is fixed now. So I guess that we can close this issue here, no?

**Comment by soywod** [comment] 2022-05-28 13:17
Not yet, the version needs to be first bumped in Himalaya. Then we can try again and assert that everything works well. I did not have time yet to take care of it, but PRs are always welcomed @TornaxO7 :smile:

**Comment by TornaxO7** [comment] 2022-05-29 08:56
@soywod can you assign me this because I don't have the permission to assign myself to this issue xD

**Comment by TornaxO7** [comment] 2022-06-03 15:34
@sbromberger hm... I can't really reproduce your issue here. I used the following:

```
To: \\""TornaxO7 \\"" <yeet@gmail.com>
```

and everything worked for me, could you please try it again on the development branch please and provide some more detailed steps?

**Comment by TornaxO7** [comment] 2022-06-03 15:40
I entered the following with `cargo run -- write`

```
Content-Type: text/plain; charset=utf-8
From: "I use arch by the way" <some-mail@yeet.com>
To: \\""What the hell is this\\"" <some-mail@yeet.com>
Subject: Test

Yeet

-- 
My signature
```

**Comment by sbromberger** [comment] 2022-06-03 16:26
I don't have access to that email anymore so I can't test. I did send it to @soywod back in February; perhaps he has it? He was able to reproduce the issue.

**Comment by soywod** [comment] 2022-06-03 21:24
> I entered the following with `cargo run -- write`
> 
> ```
> Content-Type: text/plain; charset=utf-8
> From: "I use arch by the way" <some-mail@yeet.com>
> To: \\""What the hell is this\\"" <some-mail@yeet.com>
> Subject: Test
> 
> Yeet
> 
> -- 
> My signature
> ```

You need a comma inside the double quote part, try with sth like `"Last, First" <test@localhost>`.

**Comment by TornaxO7** [comment] 2022-06-04 08:26
Oh ok, I'm able to reproduce this issue now as well

**Comment by soywod** [comment] 2022-06-04 09:20
The new version of `lettre` seems to fix the issue, the next release will contain the fix! Thanks @TornaxO7

**Closed by soywod** 2022-06-04 09:20 UTC
Labels: bug, cli
