### ISSUE TITLE
Unable to parse status response

### ISSUE THREAD

**Issue by andreivolt** [soywod/himalaya#269] opened 2021-12-03 22:41 UTC
`mailboxes` works fine though, so authentication is set up correctly and works, but otherwise get this error - and nothing extra with `--log-level trace`

**Comment by jrogers512** [comment] 2021-12-05 02:55
`$  cat ~/.config/himalaya/config.toml
# https://github.com/soywod/himalaya/wiki/Configuration:config-file

name = "J Rogers"
downloads-dir = "/home/jrogers/Downloads"
signature = """
--
Regards,
"""

[gmail]
default = true
email = "jrogers512@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "jrogers512@gmail.com"
imap-passwd-cmd = "pass show gmail"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "jrogers512@gmail.com"
smtp-passwd-cmd = "pass show gmail"

$ himalaya
Error: cannot select mailbox "INBOX"

Caused by:
    Unable to parse status response

$ himalaya --version
himalaya 0.5.1`

Same issue?  Fresh install, first time using (trying) himalaya

**Comment by soywod** [comment] 2021-12-05 08:11
It may be because of the name of the inbox mailbox. The default one is `INBOX`, but I'm pretty sure it is not the case on gmail. Could you check please the name of your inbox mailbox with the command `himalaya mbox`?

**Comment by andreivolt** [comment] 2021-12-05 09:24
Is is named INBOX in Gmail as well.

I get the same error with other mailboxes as well.

**Comment by soywod** [comment] 2021-12-05 09:33
I can't reproduce with my gmail account:

```toml
# ~/.config/himalaya/config.toml

[gmail]
email = "clement.douin@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "clement.douin@gmail.com"
imap-passwd-cmd = "pass show gmail"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "clement.douin@gmail.com"
smtp-passwd-cmd = "pass show gmail"
```

```bash
himalaya -a gmail mbox

DELIM │NAME              │ATTRIBUTES               
/     │Archives          │\HasNoChildren           
/     │Drafts            │\HasNoChildren           
/     │INBOX             │\HasNoChildren           
/     │Sent              │\HasNoChildren           
/     │Trash             │\HasNoChildren           
/     │[Gmail]           │\HasChildren, NoSelect   
/     │[Gmail]/Bin       │\HasNoChildren, \Trash   
/     │[Gmail]/Drafts    │\Drafts, \HasNoChildren  
/     │[Gmail]/Sent Mail │\HasNoChildren, \Sent    
/     │[Gmail]/Spam      │\HasNoChildren, \Junk    
/     │[Gmail]/Starred   │\Flagged, \HasNoChildren 
```

And the `himalaya -a gmail list` works as expected for me. Could you share the result of your `himalaya mbox`?

**Comment by andreivolt** [comment] 2021-12-05 13:43
looks a bit different then you:

```
DELIM │NAME              │ATTRIBUTES
/     │INBOX             │\HasNoChildren
/     │Notes             │\HasNoChildren
/     │[Gmail]           │\HasChildren, NoSelect
/     │[Gmail]/All Mail  │\All, \HasNoChildren
/     │[Gmail]/Chats     │\HasNoChildren
/     │[Gmail]/Drafts    │\Drafts, \HasNoChildren
/     │[Gmail]/Important │\HasNoChildren, \Important
/     │[Gmail]/Sent Mail │\HasNoChildren, \Sent
/     │[Gmail]/Spam      │\HasNoChildren, \Junk
/     │[Gmail]/Starred   │\Flagged, \HasNoChildren
/     │[Gmail]/Trash     │\HasNoChildren, \Trash
```

```
 himalaya -m '[Gmail]/All Mail' list
Error: cannot select mailbox "[Gmail]/All Mail"

Caused by:
    Unable to parse status response
```

**Comment by soywod** [comment] 2021-12-05 13:46
And with `INBOX` you have the same response :thinking:? It is really strange

**Comment by andreivolt** [comment] 2021-12-05 13:58
Yes.

I wonder where the differences in folder lists come from, odd.

**Comment by andreivolt** [comment] 2021-12-11 17:14
As a proposal, if you have any debugging snippet I could test out (no Rust experience), I would gladly give it a shot and report back!

**Comment by soywod** [comment] 2021-12-13 12:55
It's a good idea, I will try to provide you this whenever I can!

**Comment by ibuclaw** [comment] 2022-01-12 10:59
FYI, I've seen the same thing using davmail as the server to connect to:
```
$ himalaya list
Error: cannot select mailbox "INBOX"

Caused by:
    Unable to parse status response
```

This is the captured output (over telnet with SSL temp-disabled)
```
$ telnet 127.0.0.1 1143
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
* OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE SPECIAL-USE] IMAP4rev1 DavMail 5.4.0-trunk server ready
a1 LOGIN abcdefg hijklmnop
a1 OK Authenticated
a2 EXAMINE "INBOX"
*  1003 EXISTS
* 4 RECENT
* OK [UIDVALIDITY 1]
* OK [UIDNEXT 5343]
* FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk)
* OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk \*)]
a2 OK [READ-ONLY] EXAMINE completed
```

Same can be observed from the server logs when himalaya is talking to davmail with SSL.
```
DEBUG [davmail.imap.ImapServer] davmail  - Connection from /127.0.0.1 on port 1143
INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:36182
DEBUG [ImapConnection-36182] davmail.exchange.ExchangeSession  - Test configuration status: 401
DEBUG [ImapConnection-36182] davmail  - > * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE SPECIAL-USE] IMAP4rev1 DavMail 5.4.0-trunk server ready
DEBUG [ImapConnection-36182] davmail  - < LOGIN ********
DEBUG [ImapConnection-36182] davmail  - > a1 OK Authenticated
DEBUG [ImapConnection-36182] davmail  - < a2 EXAMINE "INBOX"
DEBUG [ImapConnection-36182] davmail.exchange.FolderLoadThread  - Still loading INBOX (1003 messages)
DEBUG [ImapConnection-36182] davmail  - >  1003 EXISTS
DEBUG [ImapConnection-36182] davmail  - > * 4 RECENT
DEBUG [ImapConnection-36182] davmail  - > * OK [UIDVALIDITY 1]
WARN  [ImapConnection-36182] davmail.imap.ImapConnection  - Client closed connection
INFO  [ImapConnection-36182] davmail.connection  - DISCONNECT - 127.0.0.1:36182
```

**Comment by soywod** [comment] 2022-02-01 13:57
It looks like the response is not parsed properly in some specific context (I was not able to determine which one). I open an issue at [rust-imap](https://github.com/jonhoo/rust-imap/issues/220) (it is the lib used by himalaya to interact with IMAP servers).

**Comment by soywod** [comment] 2022-02-03 10:38
I was able to link himalaya's debug mode with the rust-imap debug mode. Now we have access to all IMAP logs within himalaya in trace mode. Could you build himalaya from sources (on `development` branch) and run it with trace logs to see what's happening? `RUST_LOG=trace himalaya list`.

**Comment by soywod** [comment] 2022-02-08 07:10
This feature has been shipped with the v0.5.4, so you can try the same command without building from sources!

**Comment by soywod** [comment] 2022-02-28 08:25
@andreivolt @ibuclaw any news about this issue?

**Comment by soywod** [comment] 2022-03-13 19:59
I close due to inactivity, feel free to reopen if needed!

**Comment by edersohe** [comment] 2022-10-04 01:56
I tried the 0.5.10 binary and built the 0.6 development branch and I can't get the email list of my Gmail account with the same message "Unable to parse status response", I attach the output of the commands, just i removed the password from the output.

```
❯ himalaya --version 
himalaya 0.6.0
~ 
❯ RUST_LOG=trace himalaya -a gmail list
[2022-10-04T01:44:41Z INFO  himalaya::compl::args] entering completion command matcher
[2022-10-04T01:44:41Z TRACE himalaya::config::config] >> parse config from path
[2022-10-04T01:44:41Z DEBUG himalaya::config::config] path: None
[2022-10-04T01:44:41Z TRACE himalaya::config::config] config: DeserializedConfig { display_name: Some("Eder Sosa"), signature_delim: None, signature: None, downloads_dir: None, folder_listing_page_size: None, folder_aliases: None, email_listing_page_size: None, email_reading_headers: None, email_reading_format: None, email_reading_decrypt_cmd: None, email_writing_encrypt_cmd: None, email_hooks: None, accounts: {"gmail": Imap(DeserializedImapAccountConfig { base: DeserializedBaseAccountConfig { email: "eder.sohe@gmail.com", default: None, display_name: None, signature_delim: None, signature: None, downloads_dir: None, folder_listing_page_size: None, folder_aliases: None, email_listing_page_size: None, email_reading_headers: None, email_reading_format: None, email_reading_decrypt_cmd: None, email_writing_encrypt_cmd: None, email_sender: Internal(SmtpConfig { host: "smtp.gmail.com", port: 465, starttls: None, insecure: None, login: "eder.sohe@gmail.com", passwd_cmd: "pass show eder.sohe@gmail.com" }), email_hooks: None }, backend: ImapConfig { host: "imap.gmail.com", port: 993, starttls: None, insecure: None, login: "eder.sohe@gmail.com", passwd_cmd: "pass show eder.sohe@gmail.com", notify_cmd: None, notify_query: None, watch_cmds: None } })} }
[2022-10-04T01:44:41Z TRACE himalaya::config::config] << parse config from path
[2022-10-04T01:44:41Z INFO  himalaya::domain::imap::args] entering imap command matcher
[2022-10-04T01:44:41Z TRACE himalaya::domain::email::args] matches: ArgMatches { args: {"account": MatchedArg { occurs: 1, indices: [2], vals: ["gmail"] }, "source": MatchedArg { occurs: 0, indices: [5], vals: ["inbox"] }, "output": MatchedArg { occurs: 0, indices: [3], vals: ["plain"] }, "log-level": MatchedArg { occurs: 0, indices: [4], vals: ["info"] }}, subcommand: Some(SubCommand { name: "list", matches: ArgMatches { args: {"page": MatchedArg { occurs: 0, indices: [1], vals: ["1"] }}, subcommand: None, usage: Some("USAGE:\n    himalaya list [OPTIONS]") } }), usage: Some("USAGE:\n    himalaya [OPTIONS] [SUBCOMMAND]") }
[2022-10-04T01:44:41Z DEBUG himalaya::domain::email::args] list command matched
[2022-10-04T01:44:41Z DEBUG himalaya::domain::email::handlers] page size: 10
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] create TLS builder
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] insecure: false
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] create client
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] host: imap.gmail.com
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] port: 993
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] starttls: false
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] create session
[2022-10-04T01:44:41Z DEBUG himalaya_lib::backend::imap::backend] login: eder.sohe@gmail.com
[2022-10-04T01:44:41Z DEBUG himalaya_lib::process] running command: pass show eder.sohe@gmail.com
[2022-10-04T01:44:42Z TRACE himalaya_lib::process] command output: 
    
C: a2 SELECT "INBOX"
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Forwarded $MailFlagBit0 $NotJunk $NotPhishing $Phishing $has_cal LoadRemoteImages Mail Networking NotJunk OIB-Seen- OIB-Seen-INBOX OIB-Seen-OIB/Business OIB-Seen-OIB/Entertainment OIB-Seen-OIB/Finance OIB-Seen-OIB/Groups OIB-Seen-OIB/Home OIB-Seen-OIB/Jobs OIB-Seen-OIB/Shopping OIB-Seen-OIB/Social OIB-Seen-OIB/Social Networking OIB-Seen-[Gmail]/All Mail OIB-Seen-[Gmail]/Important OIB-Seen-[Gmail]/Spam OIB-Seen-[Gmail]/Trash Old receipt-handled)
Error: cannot select mailbox INBOX

Caused by:
    Unable to parse status response
~ 
❯ RUST_LOG=trace himalaya -a gmail mailbox
[2022-10-04T01:44:52Z INFO  himalaya::compl::args] entering completion command matcher
[2022-10-04T01:44:52Z TRACE himalaya::config::config] >> parse config from path
[2022-10-04T01:44:52Z DEBUG himalaya::config::config] path: None
[2022-10-04T01:44:52Z TRACE himalaya::config::config] config: DeserializedConfig { display_name: Some("Eder Sosa"), signature_delim: None, signature: None, downloads_dir: None, folder_listing_page_size: None, folder_aliases: None, email_listing_page_size: None, email_reading_headers: None, email_reading_format: None, email_reading_decrypt_cmd: None, email_writing_encrypt_cmd: None, email_hooks: None, accounts: {"gmail": Imap(DeserializedImapAccountConfig { base: DeserializedBaseAccountConfig { email: "eder.sohe@gmail.com", default: None, display_name: None, signature_delim: None, signature: None, downloads_dir: None, folder_listing_page_size: None, folder_aliases: None, email_listing_page_size: None, email_reading_headers: None, email_reading_format: None, email_reading_decrypt_cmd: None, email_writing_encrypt_cmd: None, email_sender: Internal(SmtpConfig { host: "smtp.gmail.com", port: 465, starttls: None, insecure: None, login: "eder.sohe@gmail.com", passwd_cmd: "pass show eder.sohe@gmail.com" }), email_hooks: None }, backend: ImapConfig { host: "imap.gmail.com", port: 993, starttls: None, insecure: None, login: "eder.sohe@gmail.com", passwd_cmd: "pass show eder.sohe@gmail.com", notify_cmd: None, notify_query: None, watch_cmds: None } })} }
[2022-10-04T01:44:52Z TRACE himalaya::config::config] << parse config from path
[2022-10-04T01:44:52Z INFO  himalaya::domain::imap::args] entering imap command matcher
[2022-10-04T01:44:52Z DEBUG himalaya::domain::folder::args] folders command matched
[2022-10-04T01:44:52Z TRACE himalaya_lib::backend::imap::backend] >> get imap folders
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] create TLS builder
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] insecure: false
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] create client
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] host: imap.gmail.com
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] port: 993
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] starttls: false
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] create session
[2022-10-04T01:44:52Z DEBUG himalaya_lib::backend::imap::backend] login: eder.sohe@gmail.com
[2022-10-04T01:44:52Z DEBUG himalaya_lib::process] running command: pass show eder.sohe@gmail.com
[2022-10-04T01:44:52Z TRACE himalaya_lib::process] command output: 
    
C: a2 LIST "" *
S: * LIST (\HasNoChildren) "/" "Archive"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: * LIST (\HasChildren \Noselect) "/" "[Gmail]"
S: * LIST (\Drafts \HasNoChildren) "/" "[Gmail]/Drafts"
S: * LIST (\HasNoChildren \Important) "/" "[Gmail]/Important"
S: * LIST (\HasNoChildren \Sent) "/" "[Gmail]/Sent Mail"
S: * LIST (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
S: * LIST (\Flagged \HasNoChildren) "/" "[Gmail]/Starred"
S: * LIST (\HasNoChildren \Trash) "/" "[Gmail]/Trash"
S: a2 OK Success
[2022-10-04T01:44:52Z TRACE himalaya_lib::backend::imap::backend] imap folders: Folders([Folder { delim: "/", name: "Archive", desc: "HasNoChildren" }, Folder { delim: "/", name: "INBOX", desc: "HasNoChildren" }, Folder { delim: "/", name: "[Gmail]", desc: "HasChildren, NoSelect" }, Folder { delim: "/", name: "[Gmail]/Drafts", desc: "Drafts, HasNoChildren" }, Folder { delim: "/", name: "[Gmail]/Important", desc: "HasNoChildren, Important" }, Folder { delim: "/", name: "[Gmail]/Sent Mail", desc: "HasNoChildren, Sent" }, Folder { delim: "/", name: "[Gmail]/Spam", desc: "HasNoChildren, Junk" }, Folder { delim: "/", name: "[Gmail]/Starred", desc: "Flagged, HasNoChildren" }, Folder { delim: "/", name: "[Gmail]/Trash", desc: "HasNoChildren, Trash" }])
[2022-10-04T01:44:52Z TRACE himalaya_lib::backend::imap::backend] << get imap folders
[2022-10-04T01:44:52Z TRACE himalaya::domain::folder::handlers] folders: Folders([Folder { delim: "/", name: "Archive", desc: "HasNoChildren" }, Folder { delim: "/", name: "INBOX", desc: "HasNoChildren" }, Folder { delim: "/", name: "[Gmail]", desc: "HasChildren, NoSelect" }, Folder { delim: "/", name: "[Gmail]/Drafts", desc: "Drafts, HasNoChildren" }, Folder { delim: "/", name: "[Gmail]/Important", desc: "HasNoChildren, Important" }, Folder { delim: "/", name: "[Gmail]/Sent Mail", desc: "HasNoChildren, Sent" }, Folder { delim: "/", name: "[Gmail]/Spam", desc: "HasNoChildren, Junk" }, Folder { delim: "/", name: "[Gmail]/Starred", desc: "Flagged, HasNoChildren" }, Folder { delim: "/", name: "[Gmail]/Trash", desc: "HasNoChildren, Trash" }])

[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell widths: [5, 17, 24]
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table width: 51
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 4
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 14
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 4
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 21
DELIM │NAME              │DESC                     
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 7
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 11
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 13
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 12
/     │Archive           │HasNoChildren            
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 13
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 13
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 12
/     │INBOX             │HasNoChildren            
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 7
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 11
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 21
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 4
/     │[Gmail]           │HasChildren, NoSelect    
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 14
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 4
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 21
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 4
/     │[Gmail]/Drafts    │Drafts, HasNoChildren    
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 1
/     │[Gmail]/Important │HasNoChildren, Important 
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 19
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 6
/     │[Gmail]/Sent Mail │HasNoChildren, Sent      
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 12
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 6
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 19
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 6
/     │[Gmail]/Spam      │HasNoChildren, Junk      
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 15
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 3
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 22
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 3
/     │[Gmail]/Starred   │Flagged, HasNoChildren   
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 1
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 17
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 13
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] table is not overflowing or cell is not shrinkable
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell width: 24
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] cell unicode width: 20
[2022-10-04T01:44:52Z TRACE himalaya::ui::table::table] number of spaces added to value: 5
/     │[Gmail]/Trash     │HasNoChildren, Trash     
```

**Comment by edersohe** [comment] 2022-10-05 20:09
> I close due to inactivity, feel free to reopen if needed!

I have the same issue with versions 0.5.10 and 0.6.0(develop branch), can we reopen this issue or do we need to open another one?.

**Comment by soywod** [comment] 2022-10-05 20:39
I transferred the logs to https://github.com/jonhoo/rust-imap/issues/220, let's see!

**Comment by soywod** [comment] 2022-12-16 13:34
The problem has been identified: it comes from some unknown providers who use invalid character `]` in custom IMAP flags. For example `OIB-Seen-[Gmail]/Important`. @edersohe any idea where those custom flags could come from? Anyway, it seems to be a common issue (see https://github.com/jonhoo/rust-imap/issues/220#issuecomment-1346584374), the character has finally been accepted as an exception in the parser (https://github.com/djc/tokio-imap/pull/144), I am just waiting for a new release from https://github.com/jonhoo/rust-imap/issues/220, then I will be able to deploy the new release #433. Thank you for you help!

**Closed by soywod** 2022-12-16 13:34 UTC
Labels: bug, pending
