### ISSUE TITLE
Scandinavian letters not shown properly in name

### ISSUE THREAD

**Issue by Rabalder9** [soywod/himalaya#396] opened 2022-06-27 20:41 UTC
in my config.toml I have this line

name = "æøå"

yet when I send an email to someone, (at least in Outlook) it looks all janky. Like this: "Ã¦Ã¸Ã¥". I guess it has to do with utf-8? These are scandinavian letters if it helps.

**Comment by soywod** [comment] 2022-06-27 21:03
Possible duplicate of #363?

**Closed as completed** 2022-06-28 13:03 UTC

**Comment by soywod** [comment] 2022-06-28 14:15
I will try to fix the issue ASAP, I let you know!
