### ISSUE TITLE
range expr for delete command

### ISSUE THREAD

**Issue by fancycade** [soywod/himalaya#180] opened 2021-07-09 14:50 UTC
It would be nice if the user could specify a range of uid's to delete.

Something like this:

```
himalaya delete 1772..1780
```

Obviously taking influence from Rust's range expressions.

**Comment by soywod** [comment] 2021-07-09 15:15
Duplicate of https://github.com/soywod/himalaya/issues/85 and https://github.com/soywod/himalaya/issues/119. I keep for after the `v1.0.0`.

**Closed by soywod** 2021-07-09 15:15 UTC
