### ISSUE TITLE
allow for html processor

### ISSUE THREAD

**Issue by wucke13** [soywod/himalaya#260] opened 2021-11-14 08:41 UTC
Hi, I would like to be able to set `elinks -dump /dev/stdin` as html processor. So everytime when I view a html mail, himalaya pipes it through my html processor of choice to make the html a bit more readable.

**Comment by soywod** [comment] 2021-11-14 10:42
Related to https://github.com/soywod/himalaya/issues/168 and duplicate of https://github.com/soywod/himalaya/issues/178. It is a feature I need to think well about (in a generic way), so we could set up more of those "hooks".

**Closed by soywod** 2021-11-14 10:42 UTC
